apiVersion: v1
kind: Service
metadata:
  name: tfserving-test-half-plus-two
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  selector:
    app: tfserving-test-half-plus-two